[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = [
  "probe-run",
  "--chip",
  "nRF52840_xxAA",
  "--log-format",
  "{t} [ {L}] {f}:{l} {s}",
]

[build]
target = "thumbv7em-none-eabihf"
rustflags = ["-Z", "macro-backtrace"]

[env]
DEFMT_LOG = "debug,rumcake::keyboard=off"
